using System.Globalization;
using CommunityToolkit.Mvvm.ComponentModel;

namespace CrosshairStudio.Infrastructure.Localization;

public sealed class Loc : ObservableObject
{
    public static Loc Current { get; }

    private static readonly Dictionary<string, string> En;
    private static readonly Dictionary<string, string> Ru;
    private static readonly Dictionary<string, Dictionary<string, string>> Tables;

    static Loc()
    {
        En = CreateEnglish();
        Ru = CreateRussian();
        Tables = new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = En,
            ["ru"] = Ru
        };
        Current = new Loc();
    }

    private Dictionary<string, string> _active;

    public Loc()
    {
        Language = GuessLanguage();
        _active = Tables.TryGetValue(Language, out var table) ? table : En;
    }

    public string Language { get; private set; } = "en";

    public IReadOnlyList<LanguageOption> Languages { get; } =
    [
        new("en", "English"),
        new("ru", "Русский")
    ];

    public string this[string key]
    {
        get
        {
            if (string.IsNullOrEmpty(key))
                return string.Empty;
            return _active.TryGetValue(key, out var value) ? value : key;
        }
    }

    public void SetLanguage(string? language)
    {
        var code = language != null && language.StartsWith("ru", StringComparison.OrdinalIgnoreCase) ? "ru" : "en";
        var table = Tables.TryGetValue(code, out var found) ? found : En;
        if (code == Language && ReferenceEquals(_active, table))
            return;

        Language = code;
        _active = table;
        OnPropertyChanged(string.Empty);
        OnPropertyChanged("Item[]");
        LanguageChanged?.Invoke();
    }

    public event Action? LanguageChanged;

    public static string GuessLanguage()
    {
        var ui = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return ui.Equals("ru", StringComparison.OrdinalIgnoreCase) ? "ru" : "en";
    }

    private static Dictionary<string, string> CreateEnglish() => new()
    {
        ["appName"] = "Crosshair Studio",
        ["chromeMin"] = "Minimize",
        ["chromeMax"] = "Maximize",
        ["chromeClose"] = "Close",
        ["statusReady"] = "Ready",
        ["statusLive"] = "On screen",
        ["navCrosshair"] = "Crosshair",
        ["navWidgets"] = "Overlays",
        ["navWorkshop"] = "Workshop",
        ["navSettings"] = "Settings",
        ["profiles"] = "PROFILES",
        ["preview"] = "Preview",
        ["actualSize"] = "Actual size",
        ["btnNew"] = "New",
        ["btnCopy"] = "Copy",
        ["btnSave"] = "Save",
        ["btnReset"] = "Reset",
        ["btnExport"] = "Export",
        ["btnImport"] = "Import",
        ["btnDelete"] = "Delete",
        ["btnCancel"] = "Cancel",
        ["confirmDelete"] = "Delete this profile?",
        ["overlayShow"] = "Show overlays",
        ["overlayHide"] = "Hide overlays",
        ["tabShape"] = "Shape",
        ["tabLook"] = "Tune",
        ["tabLayers"] = "Parts",
        ["tabScreen"] = "Screen",
        ["sectionShape"] = "SHAPE",
        ["sectionColor"] = "COLOR",
        ["sectionSize"] = "SIZE",
        ["sectionArms"] = "ARMS",
        ["sectionRings"] = "RINGS",
        ["sectionMarks"] = "MARKS",
        ["sectionMotion"] = "MOTION",
        ["sectionOffset"] = "OFFSET",
        ["sectionDisplay"] = "DISPLAY",
        ["sectionExtras"] = "EXTRA PARTS",
        ["sectionDesigns"] = "MY DESIGNS",
        ["sectionProfile"] = "PROFILE",
        ["addDesign"] = "New",
        ["createDesign"] = "New crosshair",
        ["createHint"] = "Give it a name and a short note. You can keep editing the shape, colors and extra parts after you create it.",
        ["designName"] = "Name",
        ["designDescription"] = "Description",
        ["designDefaultName"] = "My crosshair",
        ["btnCreate"] = "Create",
        ["showInWorkshop"] = "Show in Workshop",
        ["createWidget"] = "Widget builder",
        ["createWidgetHint"] = "Name it, pick the look, write what it shows, then choose what a click or a key does. You can mix a live template with a zoom lens.",
        ["widgetCustom"] = "Custom",
        ["widgetCustomHint"] = "Constructor: look, live text, click/key actions, optional zoom.",
        ["widgetCustomDefault"] = "Custom overlay",
        ["widgetTemplate"] = "My layout",
        ["widgetTemplateHint"] = "Your text, look, and what a click or key does.",
        ["widgetMakerGuide"] = "Constructor",
        ["widgetMakerBody"] = "Look → what it shows (tokens) → what a click/key does → optional zoom. Tokens: {time} {date} {hh} {mm} {ss} {count} {cpu} {ram} {ping} {session} {name} {left} {right}",
        ["widgetLook"] = "Look",
        ["widgetChromeGlass"] = "Glass",
        ["widgetChromePlain"] = "Plain",
        ["widgetChromeFrame"] = "Box",
        ["widgetChromeSticky"] = "Sticky note",
        ["widgetImage"] = "Image",
        ["widgetImageBrowse"] = "Choose…",
        ["widgetImageClear"] = "Remove",
        ["widgetTemplateLabel"] = "Display",
        ["widgetTemplatePlaceholder"] = "{time}   K {count}",
        ["widgetTokens"] = "Insert",
        ["widgetClick"] = "On click / key",
        ["widgetClickNone"] = "Nothing",
        ["widgetClickInc"] = "+1",
        ["widgetClickDec"] = "−1",
        ["widgetClickReset"] = "Reset",
        ["widgetClickToggle"] = "Toggle",
        ["widgetUseZoom"] = "Also add a zoom lens",
        ["widgetZoomSource"] = "Zoom area",
        ["widgetZoomTrigger"] = "Zoom when",
        ["widgetZoomClick"] = "Click the chip",
        ["widgetZoomToggle"] = "Key press (on/off)",
        ["widgetZoomHold"] = "Hold key",
        ["widgetZoomAim"] = "Around the crosshair",
        ["widgetZoomPinned"] = "Pinned area (drag the yellow box)",
        ["widgetOutput"] = "Lens size",
        ["widgetLensCenter"] = "Place in screen center",
        ["widgetLensX"] = "Lens X",
        ["widgetLensY"] = "Lens Y",
        ["widgetNote"] = "Note",
        ["addNote"] = "Add note",
        ["widgetNoteW"] = "Note width",
        ["widgetNoteH"] = "Note height",
        ["overlayEditNotes"] = "Click a sticky note to type. Drag the top strip to move it. Drag the yellow SRC box to pick the zoom area, drag the lens to move it, and drag the corner to resize.",
        ["widgetBindKey"] = "Bind key",
        ["widgetKeyNone"] = "No key",
        ["widgetKeyPress"] = "Press a key or Mouse 4 / 5…",
        ["widgetKeyClear"] = "Clear key",
        ["removeWidget"] = "Remove widget",
        ["workshopTitle"] = "Workshop",
        ["workshopHint"] = "Community crosshairs and widgets. Like what you use, add it to your library, or uncheck “Show in Workshop” to keep a design private.",
        ["workshopCrosshairs"] = "Crosshairs",
        ["workshopWidgets"] = "Widgets",
        ["workshopSearch"] = "Search",
        ["workshopSortLikes"] = "Top",
        ["workshopSortNew"] = "New",
        ["workshopAdd"] = "Add",
        ["workshopLoading"] = "Loading…",
        ["workshopEmpty"] = "Nothing listed yet.",
        ["workshopCount"] = "{0} listed",
        ["workshopOffline"] = "Workshop is offline. Check the server URL in Settings.",
        ["workshopAdded"] = "Added to your library.",
        ["workshopAddFail"] = "Could not add this item.",
        ["settingsName"] = "Display name",
        ["settingsWorkshopUrl"] = "Workshop server",
        ["deleteDesign"] = "Delete design",
        ["colorShape"] = "Shape",
        ["colorLines"] = "Lines",
        ["colorDot"] = "Center dot",
        ["colorOutline"] = "Outline",
        ["colorInner"] = "Inner ring",
        ["colorOuter"] = "Outer ring",
        ["colorGlow"] = "Glow",
        ["dragHint"] = "Drag extra parts on the preview, or use X / Y sliders.",
        ["partsBoundTo"] = "Extra parts belong to “{0}”. Switch designs to edit another set.",
        ["partsBoundHint"] = "Extra parts are saved with the current crosshair. Adding one creates a design in My crosshairs.",
        ["labelPartX"] = "X",
        ["labelPartY"] = "Y",
        ["shapeCross"] = "Cross",
        ["shapeX"] = "X",
        ["shapeCircle"] = "Circle",
        ["shapeDot"] = "Dot",
        ["shapeSquare"] = "Square",
        ["shapeDiamond"] = "Diamond",
        ["shapeTriangle"] = "Triangle",
        ["shapeHex"] = "Hex",
        ["shapeBrackets"] = "Brackets",
        ["shapeChevron"] = "Chevron",
        ["shapeStar"] = "Star",
        ["shapeArc"] = "Arc",
        ["shapeCustom"] = "Custom",
        ["labelSize"] = "Size",
        ["labelThickness"] = "Thickness",
        ["labelOpacity"] = "Opacity",
        ["labelGap"] = "Gap",
        ["labelGapH"] = "Gap H",
        ["labelGapV"] = "Gap V",
        ["labelSplitGap"] = "Split H / V gap",
        ["labelAxes"] = "Independent axes",
        ["labelWidth"] = "Width",
        ["labelHeight"] = "Height",
        ["labelRotate"] = "Rotate",
        ["labelLineCap"] = "Line cap",
        ["labelArc"] = "Arc",
        ["labelCorners"] = "Corners",
        ["labelFill"] = "Fill shape",
        ["labelOutline"] = "Outline",
        ["labelCenterDot"] = "Center dot",
        ["labelDotShape"] = "Dot shape",
        ["labelDotSize"] = "Dot size",
        ["labelLength"] = "Length",
        ["labelLine"] = "Line",
        ["labelInner"] = "Inner circle",
        ["labelOuter"] = "Outer ring",
        ["labelStroke"] = "Stroke",
        ["labelTicks"] = "Mil ticks",
        ["labelCount"] = "Count",
        ["labelSpacing"] = "Spacing",
        ["labelMidDots"] = "Mid-arm dots",
        ["labelBrackets"] = "Side brackets",
        ["labelBloom"] = "Soft bloom",
        ["labelAmount"] = "Amount",
        ["labelPulse"] = "Pulse",
        ["labelSpeed"] = "Speed",
        ["labelAimX"] = "Aim X",
        ["labelAimY"] = "Aim Y",
        ["armTop"] = "Top",
        ["armBottom"] = "Bottom",
        ["armLeft"] = "Left",
        ["armRight"] = "Right",
        ["refreshDisplays"] = "Refresh displays",
        ["alwaysOnTop"] = "Always on top",
        ["clickThrough"] = "Click through",
        ["physicalPixels"] = "Same pixel size on every DPI",
        ["offsetX"] = "Offset X",
        ["offsetY"] = "Offset Y",
        ["screenHint"] = "Works on Windows, macOS, Ubuntu, Fedora, Debian and SteamOS (X11 / XWayland). Fullscreen Wayland games may hide overlays.",
        ["addPart"] = "Add part",
        ["removePart"] = "Remove",
        ["partRing"] = "Ring",
        ["partDot"] = "Dot",
        ["partCross"] = "Cross",
        ["partX"] = "X",
        ["partArc"] = "Arc",
        ["partDiamond"] = "Diamond",
        ["partSquare"] = "Square",
        ["partTicks"] = "Ticks",
        ["partBrackets"] = "Brackets",
        ["partEnabled"] = "On",
        ["widgetsTitle"] = "Game overlays",
        ["widgetsHint"] = "Light HUD widgets. Place them anywhere with X / Y, or press the overlay hotkey and drag them on screen.",
        ["widgetClock"] = "Clock",
        ["widgetClockHint"] = "Local time in the corner.",
        ["widgetSession"] = "Session",
        ["widgetSessionHint"] = "Time since overlays were shown.",
        ["widgetStopwatch"] = "Stopwatch",
        ["widgetStopwatchHint"] = "Manual timer for rounds.",
        ["widgetCountdown"] = "Countdown",
        ["widgetCountdownHint"] = "Bomb / round countdown.",
        ["widgetSystem"] = "System",
        ["widgetSystemHint"] = "Studio CPU and PC memory. Not game FPS.",
        ["widgetPing"] = "Ping",
        ["widgetPingHint"] = "ICMP to a host every 3 seconds.",
        ["widgetNotes"] = "Notes",
        ["widgetNotesHint"] = "Sticky notes on the overlay. Add as many as you want. In overlay settings, click one to type.",
        ["widgetDate"] = "Date",
        ["widgetDateHint"] = "Local date next to the clock.",
        ["widgetBattery"] = "Battery",
        ["widgetBatteryHint"] = "Laptop charge. Shows AC on a desktop.",
        ["widgetNetwork"] = "Network",
        ["widgetNetworkHint"] = "Download and upload speed of the PC, not the game.",
        ["widgetUptime"] = "Uptime",
        ["widgetUptimeHint"] = "How long this PC has been on.",
        ["widgetDisplay"] = "Display",
        ["widgetDisplayHint"] = "Selected monitor resolution and scale.",
        ["widgetCpu"] = "CPU",
        ["widgetCpuHint"] = "Studio process CPU. Not game FPS.",
        ["widgetRam"] = "Memory",
        ["widgetRamHint"] = "PC RAM used / total.",
        ["widgetDisk"] = "Disk",
        ["widgetDiskHint"] = "Free space on the system drive.",
        ["widgetCounter"] = "Counter",
        ["widgetCounterHint"] = "Kills, rounds or any tally. Change it here — the overlay is click-through.",
        ["widgetScore"] = "Score",
        ["widgetScoreHint"] = "Two numbers for match score.",
        ["widgetActiveApp"] = "Active app",
        ["widgetActiveAppHint"] = "Title of the window in front.",
        ["widgetMagnifier"] = "Zoom",
        ["widgetMagnifierHint"] = "Live zoom of a screen slice. In overlay settings, drag the yellow SRC box to pick the area and drag the lens to place the output.",
        ["widgetMagnifierToggle"] = "Toggle zoom",
        ["widgetFunction"] = "Function",
        ["widgetZoom"] = "Zoom",
        ["widgetCapture"] = "Area",
        ["widgetSourceX"] = "Source X",
        ["widgetSourceY"] = "Source Y",
        ["widgetFollowCursor"] = "Follow cursor",
        ["widgetCounterLabel"] = "Label",
        ["widgetEnabled"] = "Show",
        ["widgetAnchor"] = "Anchor",
        ["widgetLayoutX"] = "Screen X",
        ["widgetLayoutY"] = "Screen Y",
        ["widgetScale"] = "Scale",
        ["widgetColor"] = "Color",
        ["widgetHost"] = "Host",
        ["widgetNotesText"] = "Text",
        ["widgetSeconds"] = "Seconds",
        ["widgetStart"] = "Start",
        ["widgetPause"] = "Pause",
        ["widgetReset"] = "Reset",
        ["showCrosshair"] = "Show crosshair overlay",
        ["settingsLanguage"] = "Language",
        ["settingsAbout"] = "A quiet overlay studio for aiming and in-game HUD. Overlays stay tiny, click-through, and idle when nothing changes.",
        ["settingsHotkey"] = "Overlay hotkey",
        ["settingsHotkeyBody"] = "Opens overlay settings over the game, like Discord. Widgets can be dragged while the panel is open. The same combo or Esc closes it.",
        ["hotkeyPress"] = "Press a combo…",
        ["hotkeyReset"] = "Reset",
        ["overlayEditorTitle"] = "Overlay settings",
        ["overlayEditorHint"] = "Drag widgets. Click a note to type. {0} or Esc closes this panel. Overlays stay on top.",
        ["overlayEditorDone"] = "Done",
        ["settingsPerf"] = "Performance",
        ["settingsPerfBody"] = "No blur on overlays. No background timers unless a widget needs them. The editor does not render while you play — only the small overlay windows do.",
        ["skip"] = "Skip",
        ["continue"] = "Continue",
        ["getStarted"] = "Get started",
        ["onboard0Title"] = "Welcome",
        ["onboard0Body"] = "A quiet overlay studio for aiming and in-game HUD. It sits on top of the game, stays out of the way, and looks the same on every display.",
        ["onboard0Caption"] = "Windows, macOS, Linux",
        ["onboard1Title"] = "Choose a shape",
        ["onboard1Body"] = "Pick a crosshair from live previews. Then add rings, ticks and extra parts — what you see is what appears on screen.",
        ["onboard1Caption"] = "13 shapes + extra parts",
        ["onboard2Title"] = "Game overlays",
        ["onboard2Body"] = "Clock, session timer, countdown, ping and notes. Each widget is a tiny click-through window, so games keep the GPU.",
        ["onboard2Caption"] = "Low overhead",
        ["onboard3Title"] = "Any screen",
        ["onboard3Body"] = "Pick a monitor. Portrait, ultrawide and mixed DPI are handled. Pixel-perfect keeps the same size on 1080p and 4K.",
        ["onboard3Caption"] = "Multi-display",
        ["onboard4Title"] = "You’re set",
        ["onboard4Body"] = "Show overlays when you play. Clicks pass through, so the game stays in control. Hide them from the same button.",
        ["onboard4Caption"] = "Ready",
        ["exportTitle"] = "Export profile",
        ["importTitle"] = "Import profile",
        ["anchorCenter"] = "Center",
        ["anchorTopLeft"] = "Top left",
        ["anchorTopRight"] = "Top right",
        ["anchorBottomLeft"] = "Bottom left",
        ["anchorBottomRight"] = "Bottom right",
        ["anchorTop"] = "Top",
        ["anchorBottom"] = "Bottom"
    };

    private static Dictionary<string, string> CreateRussian() => new()
    {
        ["appName"] = "Crosshair Studio",
        ["chromeMin"] = "Свернуть",
        ["chromeMax"] = "Развернуть",
        ["chromeClose"] = "Закрыть",
        ["statusReady"] = "Готово",
        ["statusLive"] = "На экране",
        ["navCrosshair"] = "Прицел",
        ["navWidgets"] = "Оверлеи",
        ["navWorkshop"] = "Мастерская",
        ["navSettings"] = "Настройки",
        ["profiles"] = "ПРОФИЛИ",
        ["preview"] = "Превью",
        ["actualSize"] = "Реальный размер",
        ["btnNew"] = "Новый",
        ["btnCopy"] = "Копия",
        ["btnSave"] = "Сохранить",
        ["btnReset"] = "Сбросить",
        ["btnExport"] = "Экспорт",
        ["btnImport"] = "Импорт",
        ["btnDelete"] = "Удалить",
        ["btnCancel"] = "Отмена",
        ["confirmDelete"] = "Удалить этот профиль?",
        ["overlayShow"] = "Показать оверлеи",
        ["overlayHide"] = "Скрыть оверлеи",
        ["tabShape"] = "Форма",
        ["tabLook"] = "Вид",
        ["tabLayers"] = "Части",
        ["tabScreen"] = "Экран",
        ["sectionShape"] = "ФОРМА",
        ["sectionColor"] = "ЦВЕТ",
        ["sectionSize"] = "РАЗМЕР",
        ["sectionArms"] = "ЛУЧИ",
        ["sectionRings"] = "КОЛЬЦА",
        ["sectionMarks"] = "МЕТКИ",
        ["sectionMotion"] = "ДВИЖЕНИЕ",
        ["sectionOffset"] = "СМЕЩЕНИЕ",
        ["sectionDisplay"] = "ДИСПЛЕЙ",
        ["sectionExtras"] = "ДОП. ЭЛЕМЕНТЫ",
        ["sectionDesigns"] = "МОИ ПРИЦЕЛЫ",
        ["sectionProfile"] = "ПРОФИЛЬ",
        ["addDesign"] = "Новый",
        ["createDesign"] = "Новый прицел",
        ["createHint"] = "Задайте имя и короткое описание. Форму, цвета и доп. элементы можно менять сразу после создания.",
        ["designName"] = "Название",
        ["designDescription"] = "Описание",
        ["designDefaultName"] = "Мой прицел",
        ["btnCreate"] = "Создать",
        ["showInWorkshop"] = "Показывать в мастерской",
        ["createWidget"] = "Конструктор виджета",
        ["createWidgetHint"] = "Имя, вид, что показывать и что делает клик или клавиша. Можно смешать живой шаблон с лупой.",
        ["widgetCustom"] = "Свой",
        ["widgetCustomHint"] = "Конструктор: вид, живой текст, действия и по желанию лупа.",
        ["widgetCustomDefault"] = "Свой оверлей",
        ["widgetTemplate"] = "Свой шаблон",
        ["widgetTemplateHint"] = "Свой текст, вид и действие по клику или клавише.",
        ["widgetMakerGuide"] = "Конструктор",
        ["widgetMakerBody"] = "Вид → что на экране (токены) → клик/клавиша → по желанию лупа. Токены: {time} {date} {hh} {mm} {ss} {count} {cpu} {ram} {ping} {session} {name} {left} {right}",
        ["widgetLook"] = "Вид",
        ["widgetChromeGlass"] = "Стекло",
        ["widgetChromePlain"] = "Текст",
        ["widgetChromeFrame"] = "Рамка",
        ["widgetChromeSticky"] = "Стикер",
        ["widgetImage"] = "Картинка",
        ["widgetImageBrowse"] = "Выбрать…",
        ["widgetImageClear"] = "Убрать",
        ["widgetTemplateLabel"] = "На экране",
        ["widgetTemplatePlaceholder"] = "{time}   K {count}",
        ["widgetTokens"] = "Вставить",
        ["widgetClick"] = "По клику / клавише",
        ["widgetClickNone"] = "Ничего",
        ["widgetClickInc"] = "+1",
        ["widgetClickDec"] = "−1",
        ["widgetClickReset"] = "Сброс",
        ["widgetClickToggle"] = "Переключить",
        ["widgetUseZoom"] = "Добавить лупу",
        ["widgetZoomSource"] = "Область лупы",
        ["widgetZoomTrigger"] = "Лупа когда",
        ["widgetZoomClick"] = "Клик по чипу",
        ["widgetZoomToggle"] = "Нажатие клавиши (вкл/выкл)",
        ["widgetZoomHold"] = "Удерживать клавишу",
        ["widgetZoomAim"] = "Вокруг прицела",
        ["widgetZoomPinned"] = "Своя область (жёлтая рамка)",
        ["widgetOutput"] = "Размер лупы",
        ["widgetLensCenter"] = "Поместить в центр экрана",
        ["widgetLensX"] = "Лупа X",
        ["widgetLensY"] = "Лупа Y",
        ["widgetNote"] = "Заметка",
        ["addNote"] = "Добавить заметку",
        ["widgetNoteW"] = "Ширина заметки",
        ["widgetNoteH"] = "Высота заметки",
        ["overlayEditNotes"] = "Нажмите на стикер, чтобы писать. Тяните за полоску сверху. Жёлтая рамка SRC — область лупы. Окно лупы можно перетащить, за угол — изменить размер.",
        ["widgetBindKey"] = "Назначить клавишу",
        ["widgetKeyNone"] = "Нет клавиши",
        ["widgetKeyPress"] = "Нажмите клавишу или Mouse 4 / 5…",
        ["widgetKeyClear"] = "Сбросить клавишу",
        ["removeWidget"] = "Удалить виджет",
        ["workshopTitle"] = "Мастерская",
        ["workshopHint"] = "Прицелы и виджеты сообщества. Лайкните, добавьте себе, или снимите «Показывать в мастерской», чтобы скрыть свой дизайн.",
        ["workshopCrosshairs"] = "Прицелы",
        ["workshopWidgets"] = "Виджеты",
        ["workshopSearch"] = "Поиск",
        ["workshopSortLikes"] = "Топ",
        ["workshopSortNew"] = "Новые",
        ["workshopAdd"] = "Добавить",
        ["workshopLoading"] = "Загрузка…",
        ["workshopEmpty"] = "Пока ничего нет.",
        ["workshopCount"] = "{0} в списке",
        ["workshopOffline"] = "Мастерская недоступна. Проверьте адрес сервера в Настройках.",
        ["workshopAdded"] = "Добавлено в библиотеку.",
        ["workshopAddFail"] = "Не удалось добавить.",
        ["settingsName"] = "Имя в мастерской",
        ["settingsWorkshopUrl"] = "Сервер мастерской",
        ["deleteDesign"] = "Удалить прицел",
        ["colorShape"] = "Форма",
        ["colorLines"] = "Линии",
        ["colorDot"] = "Центр. точка",
        ["colorOutline"] = "Обводка",
        ["colorInner"] = "Внутр. кольцо",
        ["colorOuter"] = "Внешнее кольцо",
        ["colorGlow"] = "Свечение",
        ["dragHint"] = "Перетащите элемент на превью или сдвиньте ползунками X / Y.",
        ["partsBoundTo"] = "Доп. элементы привязаны к «{0}». Переключите прицел, чтобы править другой набор.",
        ["partsBoundHint"] = "Доп. элементы сохраняются вместе с текущим прицелом. Добавление создаст прицел в «Мои прицелы».",
        ["labelPartX"] = "X",
        ["labelPartY"] = "Y",
        ["shapeCross"] = "Крест",
        ["shapeX"] = "X",
        ["shapeCircle"] = "Круг",
        ["shapeDot"] = "Точка",
        ["shapeSquare"] = "Квадрат",
        ["shapeDiamond"] = "Ромб",
        ["shapeTriangle"] = "Треугольник",
        ["shapeHex"] = "Гекс",
        ["shapeBrackets"] = "Скобки",
        ["shapeChevron"] = "Шеврон",
        ["shapeStar"] = "Звезда",
        ["shapeArc"] = "Дуга",
        ["shapeCustom"] = "Свой",
        ["labelSize"] = "Размер",
        ["labelThickness"] = "Толщина",
        ["labelOpacity"] = "Прозрачность",
        ["labelGap"] = "Зазор",
        ["labelGapH"] = "Зазор H",
        ["labelGapV"] = "Зазор V",
        ["labelSplitGap"] = "Разный зазор H / V",
        ["labelAxes"] = "Разные оси",
        ["labelWidth"] = "Ширина",
        ["labelHeight"] = "Высота",
        ["labelRotate"] = "Поворот",
        ["labelLineCap"] = "Концы линий",
        ["labelArc"] = "Дуга",
        ["labelCorners"] = "Скругление",
        ["labelFill"] = "Заливка",
        ["labelOutline"] = "Обводка",
        ["labelCenterDot"] = "Центр. точка",
        ["labelDotShape"] = "Форма точки",
        ["labelDotSize"] = "Размер точки",
        ["labelLength"] = "Длина",
        ["labelLine"] = "Линия",
        ["labelInner"] = "Внутр. круг",
        ["labelOuter"] = "Внешнее кольцо",
        ["labelStroke"] = "Обводка",
        ["labelTicks"] = "Риски",
        ["labelCount"] = "Число",
        ["labelSpacing"] = "Шаг",
        ["labelMidDots"] = "Точки на лучах",
        ["labelBrackets"] = "Боковые скобки",
        ["labelBloom"] = "Мягкое свечение",
        ["labelAmount"] = "Сила",
        ["labelPulse"] = "Пульс",
        ["labelSpeed"] = "Скорость",
        ["labelAimX"] = "Прицел X",
        ["labelAimY"] = "Прицел Y",
        ["armTop"] = "Верх",
        ["armBottom"] = "Низ",
        ["armLeft"] = "Лево",
        ["armRight"] = "Право",
        ["refreshDisplays"] = "Обновить экраны",
        ["alwaysOnTop"] = "Поверх окон",
        ["clickThrough"] = "Клики насквозь",
        ["physicalPixels"] = "Одинаковый размер на любом DPI",
        ["offsetX"] = "Сдвиг X",
        ["offsetY"] = "Сдвиг Y",
        ["screenHint"] = "Windows, macOS, Ubuntu, Fedora, Debian и SteamOS (X11 / XWayland). Полноэкранные игры на Wayland могут скрывать оверлей.",
        ["addPart"] = "Добавить элемент",
        ["removePart"] = "Убрать",
        ["partRing"] = "Кольцо",
        ["partDot"] = "Точка",
        ["partCross"] = "Крест",
        ["partX"] = "X",
        ["partArc"] = "Дуга",
        ["partDiamond"] = "Ромб",
        ["partSquare"] = "Квадрат",
        ["partTicks"] = "Риски",
        ["partBrackets"] = "Скобки",
        ["partEnabled"] = "Вкл",
        ["widgetsTitle"] = "Игровые оверлеи",
        ["widgetsHint"] = "Лёгкие HUD-виджеты. Их можно поставить куда угодно: ползунками X / Y или перетаскиванием после горячей клавиши оверлея.",
        ["widgetClock"] = "Часы",
        ["widgetClockHint"] = "Локальное время в углу.",
        ["widgetSession"] = "Сессия",
        ["widgetSessionHint"] = "Время с момента показа оверлеев.",
        ["widgetStopwatch"] = "Секундомер",
        ["widgetStopwatchHint"] = "Ручной таймер для раундов.",
        ["widgetCountdown"] = "Обратный отсчёт",
        ["widgetCountdownHint"] = "Таймер бомбы / раунда.",
        ["widgetSystem"] = "Система",
        ["widgetSystemHint"] = "CPU студии и память ПК. Это не FPS игры.",
        ["widgetPing"] = "Пинг",
        ["widgetPingHint"] = "ICMP до хоста каждые 3 секунды.",
        ["widgetNotes"] = "Заметки",
        ["widgetNotesHint"] = "Стикеры на оверлее. Можно несколько. В режиме настройки нажмите на заметку, чтобы писать.",
        ["widgetDate"] = "Дата",
        ["widgetDateHint"] = "Локальная дата рядом с часами.",
        ["widgetBattery"] = "Батарея",
        ["widgetBatteryHint"] = "Заряд ноутбука. На ПК показывает сеть.",
        ["widgetNetwork"] = "Сеть",
        ["widgetNetworkHint"] = "Скорость загрузки и отдачи ПК, не игры.",
        ["widgetUptime"] = "Аптайм",
        ["widgetUptimeHint"] = "Сколько ПК уже включён.",
        ["widgetDisplay"] = "Экран",
        ["widgetDisplayHint"] = "Разрешение и масштаб выбранного монитора.",
        ["widgetCpu"] = "CPU",
        ["widgetCpuHint"] = "CPU процесса студии. Это не FPS игры.",
        ["widgetRam"] = "Память",
        ["widgetRamHint"] = "Занятая / вся RAM компьютера.",
        ["widgetDisk"] = "Диск",
        ["widgetDiskHint"] = "Свободное место на системном диске.",
        ["widgetCounter"] = "Счётчик",
        ["widgetCounterHint"] = "Фраги, раунды или любой счёт. Меняется здесь — оверлей клики не принимает.",
        ["widgetScore"] = "Счёт",
        ["widgetScoreHint"] = "Два числа для счёта матча.",
        ["widgetActiveApp"] = "Активное окно",
        ["widgetActiveAppHint"] = "Заголовок окна на переднем плане.",
        ["widgetMagnifier"] = "Лупа",
        ["widgetMagnifierHint"] = "Живой увеличенный кусок экрана. В режиме настройки перетащите жёлтую рамку (что приближать) и само окно лупы (куда выводить).",
        ["widgetMagnifierToggle"] = "Вкл / выкл лупу",
        ["widgetFunction"] = "Функция",
        ["widgetZoom"] = "Увеличение",
        ["widgetCapture"] = "Область",
        ["widgetSourceX"] = "Источник X",
        ["widgetSourceY"] = "Источник Y",
        ["widgetFollowCursor"] = "Следить за курсором",
        ["widgetCounterLabel"] = "Подпись",
        ["widgetEnabled"] = "Показать",
        ["widgetAnchor"] = "Якорь",
        ["widgetLayoutX"] = "Экран X",
        ["widgetLayoutY"] = "Экран Y",
        ["widgetScale"] = "Масштаб",
        ["widgetColor"] = "Цвет",
        ["widgetHost"] = "Хост",
        ["widgetNotesText"] = "Текст",
        ["widgetSeconds"] = "Секунды",
        ["widgetStart"] = "Старт",
        ["widgetPause"] = "Пауза",
        ["widgetReset"] = "Сброс",
        ["showCrosshair"] = "Показывать прицел",
        ["settingsLanguage"] = "Язык",
        ["settingsAbout"] = "Тихая студия оверлеев для прицела и HUD. Окна маленькие, клики проходят насквозь, таймеры спят, если виджет выключен.",
        ["settingsHotkey"] = "Горячая клавиша оверлея",
        ["settingsHotkeyBody"] = "Открывает настройки оверлея поверх игры, как в Discord. Пока панель открыта, виджеты можно перетаскивать. Та же комбинация или Esc закрывает панель.",
        ["hotkeyPress"] = "Нажмите комбинацию…",
        ["hotkeyReset"] = "Сбросить",
        ["overlayEditorTitle"] = "Настройки оверлея",
        ["overlayEditorHint"] = "Перетащите виджеты. Нажмите на заметку, чтобы писать. {0} или Esc закрывает панель. Оверлеи всегда сверху.",
        ["overlayEditorDone"] = "Готово",
        ["settingsPerf"] = "Производительность",
        ["settingsPerfBody"] = "На оверлее нет размытия. Фоновые таймеры запускаются только для нужных виджетов. Редактор не рисуется во время игры — только маленькие окна оверлея.",
        ["skip"] = "Пропустить",
        ["continue"] = "Далее",
        ["getStarted"] = "Начать",
        ["onboard0Title"] = "Добро пожаловать",
        ["onboard0Body"] = "Тихая студия оверлеев для прицела и HUD. Она лежит поверх игры, не мешает и выглядит одинаково на любом мониторе.",
        ["onboard0Caption"] = "Windows, macOS, Linux",
        ["onboard1Title"] = "Выберите форму",
        ["onboard1Body"] = "Прицел выбирается по живому превью. Дальше можно добавить кольца, риски и свои элементы — как на превью, так и в игре.",
        ["onboard1Caption"] = "13 форм + доп. элементы",
        ["onboard2Title"] = "Игровые оверлеи",
        ["onboard2Body"] = "Часы, сессия, отсчёт, пинг и заметки. Каждый виджет — крошечное окно навылет, GPU остаётся игре.",
        ["onboard2Caption"] = "Малый расход",
        ["onboard3Title"] = "Любой экран",
        ["onboard3Body"] = "Выберите монитор. Портрет, ультравайд и разный DPI учитываются. На 1080p и 4K размер в пикселях одинаковый.",
        ["onboard3Caption"] = "Несколько дисплеев",
        ["onboard4Title"] = "Готово",
        ["onboard4Body"] = "Включите оверлеи перед игрой. Клики проходят насквозь. Тем же кнопкой их можно скрыть.",
        ["onboard4Caption"] = "Готово",
        ["exportTitle"] = "Экспорт профиля",
        ["importTitle"] = "Импорт профиля",
        ["anchorCenter"] = "Центр",
        ["anchorTopLeft"] = "Верх слева",
        ["anchorTopRight"] = "Верх справа",
        ["anchorBottomLeft"] = "Низ слева",
        ["anchorBottomRight"] = "Низ справа",
        ["anchorTop"] = "Верх",
        ["anchorBottom"] = "Низ"
    };
}

public sealed record LanguageOption(string Code, string Title)
{
    public override string ToString() => Title;
}
